server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
fdfs:
  connect-timeout: 600
  so-timeout: 2500
  thumb-image:
    width: 60
    height: 60
  tracker-list:
    - 192.168.32.128:22122
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
xxx:
  upload:
    baseUrl: http://image.xxx.com/
    allowImageTypes:
      - image/jpg
      - image/jpeg
      - image/png
      - image/bmp
    allowSongType:
      - audio/mp3
      - audio/midi
      - audio/wma
      - audio/vqf
      - audio/amr
      - audio/flac
      - application/octet-stream

